/**
 * OrbitalRates — Mock Dashboard Data
 * 
 * Realistic institutional-grade mock data for the GitHub Pages demo.
 * Simulates a full 7-layer analysis cycle on a $1B fixed-income RV portfolio.
 */

import { DashboardData } from "./api";

export const MOCK_DASHBOARD: DashboardData = {
  cycle_count: 847,
  data_source: "mock",
  is_halted: false,
  cycle_duration_ms: 14231.7,
  timestamp: new Date().toISOString(),

  // ── Layer 3: Regime Classification ──────────────────────
  regime: {
    regime: "volatile_mean_reverting",
    confidence: 0.8241,
    vol_percentile: 0.6832,
    correlation_level: 0.6145,
    liquidity_index: 0.5918,
    funding_stress: 0.3421,
    leverage_cap: 6.0,
    halflife_tolerance: 60,
    regime_duration_days: 12,
    transition_probability: {
      stable_mean_reverting: 0.30,
      volatile_mean_reverting: 0.45,
      liquidity_tightening: 0.15,
      structural_shift: 0.07,
      crisis: 0.03,
    },
  },

  // ── Layer 2: Spread Discovery ──────────────────────────
  opportunities: [
    {
      spread_id: "TLT_IEF_curve",
      spread_type: "curve",
      leg1: "TLT",
      leg2: "IEF",
      current_spread_bps: 142.5,
      zscore: -2.34,
      halflife_days: 18.2,
      ar1_coefficient: 0.962,
      is_stationary: true,
      structural_break_prob: 0.08,
      liquidity_score: 0.89,
      crowding_proxy: 0.22,
      expected_return_bps: 38.7,
      expected_shortfall_bps: -94.2,
      vol_adjusted_return: 1.84,
      tail_5pct_bps: -62.1,
      tail_1pct_bps: -118.4,
      signal: "enter_long",
      rejection_reason: undefined,
    },
    {
      spread_id: "LQD_HYG_credit",
      spread_type: "credit",
      leg1: "LQD",
      leg2: "HYG",
      current_spread_bps: 287.3,
      zscore: 2.67,
      halflife_days: 24.1,
      ar1_coefficient: 0.971,
      is_stationary: true,
      structural_break_prob: 0.12,
      liquidity_score: 0.76,
      crowding_proxy: 0.35,
      expected_return_bps: 52.1,
      expected_shortfall_bps: -128.5,
      vol_adjusted_return: 1.62,
      tail_5pct_bps: -87.3,
      tail_1pct_bps: -165.9,
      signal: "enter_short",
      rejection_reason: undefined,
    },
    {
      spread_id: "TIP_IEF_breakeven",
      spread_type: "breakeven",
      leg1: "TIP",
      leg2: "IEF",
      current_spread_bps: 231.8,
      zscore: -2.12,
      halflife_days: 32.5,
      ar1_coefficient: 0.979,
      is_stationary: true,
      structural_break_prob: 0.05,
      liquidity_score: 0.82,
      crowding_proxy: 0.18,
      expected_return_bps: 29.4,
      expected_shortfall_bps: -71.8,
      vol_adjusted_return: 1.47,
      tail_5pct_bps: -48.2,
      tail_1pct_bps: -91.6,
      signal: "enter_long",
      rejection_reason: undefined,
    },
    {
      spread_id: "MBB_GOVT_mbs",
      spread_type: "mbs_basis",
      leg1: "MBB",
      leg2: "GOVT",
      current_spread_bps: 67.2,
      zscore: 1.89,
      halflife_days: 15.7,
      ar1_coefficient: 0.956,
      is_stationary: true,
      structural_break_prob: 0.14,
      liquidity_score: 0.71,
      crowding_proxy: 0.41,
      expected_return_bps: 21.8,
      expected_shortfall_bps: -55.3,
      vol_adjusted_return: 1.21,
      tail_5pct_bps: -38.7,
      tail_1pct_bps: -72.1,
      signal: "hold",
      rejection_reason: undefined,
    },
    {
      spread_id: "SHY_FLOT_funding",
      spread_type: "floating",
      leg1: "SHY",
      leg2: "FLOT",
      current_spread_bps: 18.4,
      zscore: -0.87,
      halflife_days: 112.3,
      ar1_coefficient: 0.994,
      is_stationary: false,
      structural_break_prob: 0.42,
      liquidity_score: 0.65,
      crowding_proxy: 0.58,
      expected_return_bps: 4.2,
      expected_shortfall_bps: -31.7,
      vol_adjusted_return: 0.38,
      tail_5pct_bps: -22.1,
      tail_1pct_bps: -44.8,
      signal: "reject",
      rejection_reason: "halflife > 90d, non-stationary, crowding > 0.5",
    },
    {
      spread_id: "BNDX_BWX_intl",
      spread_type: "international",
      leg1: "BNDX",
      leg2: "BWX",
      current_spread_bps: 54.1,
      zscore: 1.42,
      halflife_days: 85.2,
      ar1_coefficient: 0.992,
      is_stationary: true,
      structural_break_prob: 0.31,
      liquidity_score: 0.48,
      crowding_proxy: 0.62,
      expected_return_bps: 8.7,
      expected_shortfall_bps: -42.3,
      vol_adjusted_return: 0.67,
      tail_5pct_bps: -29.8,
      tail_1pct_bps: -58.4,
      signal: "reject",
      rejection_reason: "structural_break > 0.3, liquidity < 0.5",
    },
  ],
  total_candidates: 12,

  // ── Layer 5: Active Positions ──────────────────────────
  positions: [
    {
      position_id: "POS_001",
      spread_id: "TLT_IEF_curve",
      spread_type: "curve",
      leg1: "TLT",
      leg2: "IEF",
      direction: "LONG",
      notional: 85_000_000,
      dv01_net: 12400,
      weight: 0.215,
      entry_spread_bps: 158.2,
      current_spread_bps: 142.5,
      entry_zscore: -2.81,
      current_zscore: -2.34,
      unrealized_pnl_bps: 15.7,
    },
    {
      position_id: "POS_002",
      spread_id: "LQD_HYG_credit",
      spread_type: "credit",
      leg1: "LQD",
      leg2: "HYG",
      direction: "SHORT",
      notional: 62_000_000,
      dv01_net: 8900,
      weight: 0.157,
      entry_spread_bps: 264.1,
      current_spread_bps: 287.3,
      entry_zscore: 2.21,
      current_zscore: 2.67,
      unrealized_pnl_bps: -23.2,
    },
    {
      position_id: "POS_003",
      spread_id: "TIP_IEF_breakeven",
      spread_type: "breakeven",
      leg1: "TIP",
      leg2: "IEF",
      direction: "LONG",
      notional: 120_000_000,
      dv01_net: 15200,
      weight: 0.303,
      entry_spread_bps: 245.6,
      current_spread_bps: 231.8,
      entry_zscore: -2.45,
      current_zscore: -2.12,
      unrealized_pnl_bps: 13.8,
    },
    {
      position_id: "POS_004",
      spread_id: "EMB_GOVT_em",
      spread_type: "credit",
      leg1: "EMB",
      leg2: "GOVT",
      direction: "LONG",
      notional: 45_000_000,
      dv01_net: 6700,
      weight: 0.114,
      entry_spread_bps: 412.8,
      current_spread_bps: 398.2,
      entry_zscore: -2.14,
      current_zscore: -1.87,
      unrealized_pnl_bps: 14.6,
    },
  ],
  total_positions: 4,

  // ── Layer 4: Risk & Survival ───────────────────────────
  risk_metrics: {
    total_dv01: 43200,
    total_convexity: 0.85,
    gross_leverage: 4.72,
    net_leverage: 2.31,
    expected_return_annual_pct: 8.42,
    expected_shortfall_99_pct: 4.21,
    var_99_pct: 2.87,
    max_stress_loss_pct: 5.14,
    survival_probability: 0.9934,
    sharpe_estimate: 1.82,
    current_drawdown_pct: 1.24,
    max_drawdown_pct: 3.67,
    liquidity_weighted_exposure: 0.68,
    correlation_risk: 0.42,
    crowding_risk: 0.28,
    funding_cost_bps: 14.3,
  },

  // ── Layer 4: Stress Scenarios ──────────────────────────
  stress_results: [
    {
      scenario_name: "2008 Spread Blowout",
      portfolio_loss_pct: 4.82,
      margin_call_triggered: false,
      survival: true,
      description: "All spreads widen 200bps — Lehman-style credit dislocation",
    },
    {
      scenario_name: "2020 Liquidity Seizure",
      portfolio_loss_pct: 3.14,
      margin_call_triggered: false,
      survival: true,
      description: "Forced liquidation at 50% haircut — March 2020 treasury market",
    },
    {
      scenario_name: "Correlation → 1",
      portfolio_loss_pct: 5.67,
      margin_call_triggered: true,
      survival: true,
      description: "All hedges fail, correlations spike to 0.95 — diversification collapse",
    },
    {
      scenario_name: "Volatility Doubling",
      portfolio_loss_pct: 2.91,
      margin_call_triggered: false,
      survival: true,
      description: "Vol multiplied by 2.0× — sudden rate uncertainty spike",
    },
    {
      scenario_name: "Funding Spike",
      portfolio_loss_pct: 1.87,
      margin_call_triggered: false,
      survival: true,
      description: "Repo rates +300bps — overnight funding crisis",
    },
    {
      scenario_name: "Forced Deleveraging",
      portfolio_loss_pct: 6.23,
      margin_call_triggered: true,
      survival: false,
      description: "50% forced unwind at 3× market impact — LTCM scenario",
    },
  ],

  // ── Layer 6: Execution Simulation ──────────────────────
  execution_results: [
    {
      spread_id: "TLT_IEF_curve",
      intended_notional: 85_000_000,
      executed_notional: 83_200_000,
      slippage_bps: 1.8,
      market_impact_bps: 0.9,
      fill_rate: 0.979,
      execution_cost_bps: 2.7,
      liquidity_available: true,
    },
    {
      spread_id: "LQD_HYG_credit",
      intended_notional: 62_000_000,
      executed_notional: 57_400_000,
      slippage_bps: 3.2,
      market_impact_bps: 2.1,
      fill_rate: 0.926,
      execution_cost_bps: 5.3,
      liquidity_available: true,
    },
    {
      spread_id: "TIP_IEF_breakeven",
      intended_notional: 120_000_000,
      executed_notional: 118_500_000,
      slippage_bps: 1.2,
      market_impact_bps: 0.6,
      fill_rate: 0.988,
      execution_cost_bps: 1.8,
      liquidity_available: true,
    },
  ],

  // ── Layer 7: Meta-Learning / Decay ─────────────────────
  decay_metrics: {
    halflife_drift_pct: 0.082,
    edge_decay_pct: 0.134,
    regime_frequency_change: 0.045,
    correlation_clustering: 0.091,
    crowding_increase: 0.167,
    retraining_recommended: false,
    parameter_adjustments: {
      zscore_entry: -0.05,
      max_halflife: 2.0,
      crowding_penalty: 0.03,
    },
  },

  // ── Governance ────────────────────────────────────────
  rejections: [
    "SHY_FLOT_funding: halflife > 90d",
    "BNDX_BWX_intl: structural_break > 0.3",
    "VCLT_VCSH_curve: liquidity < 0.5",
  ],

  audit_log: [
    {
      timestamp: new Date(Date.now() - 60_000).toISOString(),
      agent: "Layer 1 — Data",
      action: "FETCH_MARKET_DATA",
      decision: "20 symbols fetched, 0 fallbacks",
      rationale: "All ETF data retrieved via yfinance within 8.2s",
      approved: true,
    },
    {
      timestamp: new Date(Date.now() - 55_000).toISOString(),
      agent: "Layer 2 — Discovery",
      action: "SPREAD_SCAN",
      decision: "12 candidates scanned, 4 active, 2 rejected",
      rationale: "Z-score, stationarity, halflife, and liquidity filters applied",
      approved: true,
    },
    {
      timestamp: new Date(Date.now() - 50_000).toISOString(),
      agent: "Layer 3 — Regime",
      action: "CLASSIFY_REGIME",
      decision: "VOLATILE_MEAN_REVERTING (82.4%)",
      rationale: "Vol %ile 68.3%, correlation 0.61, funding stress elevated",
      approved: true,
    },
    {
      timestamp: new Date(Date.now() - 45_000).toISOString(),
      agent: "Layer 4 — Risk",
      action: "MONTE_CARLO_SIM",
      decision: "Survival prob: 99.34%, 6 stress scenarios run",
      rationale: "10,000 MC paths, Student-t(4) tails, regime vol multiplier 1.5×",
      approved: true,
    },
    {
      timestamp: new Date(Date.now() - 40_000).toISOString(),
      agent: "Layer 5 — Capital",
      action: "POSITION_SIZING",
      decision: "4 positions sized, gross leverage 4.72×",
      rationale: "Fractional Kelly f=0.3, regime adj 0.75, liquidity penalty applied",
      approved: true,
    },
    {
      timestamp: new Date(Date.now() - 35_000).toISOString(),
      agent: "Governance",
      action: "TRADE_APPROVAL",
      decision: "3/3 trades APPROVED",
      rationale: "Within region caps, type caps, leverage limits",
      approved: true,
    },
    {
      timestamp: new Date(Date.now() - 30_000).toISOString(),
      agent: "Layer 6 — Execution",
      action: "SIMULATE_EXECUTION",
      decision: "3 trades executed, avg fill rate 96.4%",
      rationale: "Slippage within bounds, liquidity sufficient",
      approved: true,
    },
    {
      timestamp: new Date(Date.now() - 25_000).toISOString(),
      agent: "Layer 7 — Meta",
      action: "DECAY_ANALYSIS",
      decision: "Edge decay 13.4%, no retraining needed",
      rationale: "Crowding increasing (+16.7%), monitoring threshold 20%",
      approved: true,
    },
    {
      timestamp: new Date(Date.now() - 10_000).toISOString(),
      agent: "Governance",
      action: "CYCLE_COMPLETE",
      decision: "Cycle #847 completed in 14.2s",
      rationale: "All 7 layers executed successfully, no kill-switch triggers",
      approved: true,
    },
  ],
};
